# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bedc91e25502f3021297aa76febeecb52a81b9e2287d4ce00bf8811bbee7a47c67d9042cf349560a9613723f7a0fbb1516250858da5e6a7f7f591f4adb95d1f9

test:
  secret_key_base: a00f927a72ccb833552e58dd7843c7bb543ad84fe65bfcf30020347d8b6c954c5ef3348c3102cda33a58e010c1bad2c9751f12ccf788bda7766fe04ae6179401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
